#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'go2-mapping','console_scripts','scan_stamp_fix'
__requires__ = 'go2-mapping'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('go2-mapping', 'console_scripts', 'scan_stamp_fix')()
    )
