/rosbridge_websocket:
  ros__parameters:
    address: "0.0.0.0"
    port: 9090
    topics_glob: "['/tf','/tf_static','/map','/map_updates','/scan_raw','/scan','/utlidar/robot_odom','/lidar_points','/plan','/local_plan','/global_costmap/costmap','/global_costmap/costmap_updates','/global_costmap/costmap_raw','/local_costmap/costmap','/local_costmap/costmap_updates','/local_costmap/costmap_raw','/particlecloud','/initialpose','/goal_pose','/robot_description','/joint_states','/from_human_text','/to_human_text','/to_human_audio','/voice_commands','/voice_nav_events','/navigate_to_pose/_action/status','/navigate_to_pose/_action/feedback','/rosout']"
